// Auto-generated SVG icon map (subset of @mdi/js actually used by the app).
// Regenerate after adding/removing icons. Using SVG icons keeps only the
// icons in use in the bundle instead of the full ~400 KB icon font CSS.
import {
  mdiAccount,
  mdiAccountCircleOutline,
  mdiAccountMultipleOutline,
  mdiAccountSupervisor,
  mdiAlertCircleOutline,
  mdiAlertOctagonOutline,
  mdiApps,
  mdiArrowDown,
  mdiArrowLeft,
  mdiArrowRight,
  mdiArrowUp,
  mdiAt,
  mdiBackupRestore,
  mdiBell,
  mdiCached,
  mdiCalendar,
  mdiCalendarImportOutline,
  mdiCardAccountMailOutline,
  mdiCheck,
  mdiCheckAll,
  mdiCheckCircle,
  mdiCheckCircleOutline,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiCircleEditOutline,
  mdiCircleSmall,
  mdiClipboardMultipleOutline,
  mdiClipboardOutline,
  mdiClipboardPlus,
  mdiClockOutline,
  mdiClose,
  mdiCloseCircle,
  mdiCloseCircleOutline,
  mdiCodeTags,
  mdiCog,
  mdiCogOutline,
  mdiContacts,
  mdiContactsOutline,
  mdiContentCopy,
  mdiContentSave,
  mdiContentSaveOutline,
  mdiDelete,
  mdiDeleteOutline,
  mdiDomain,
  mdiDotsHorizontal,
  mdiDotsVertical,
  mdiDownload,
  mdiEarth,
  mdiEmail,
  mdiEmailCheckOutline,
  mdiEmailFastOutline,
  mdiEmailOpenOutline,
  mdiEmailOutline,
  mdiEmailSyncOutline,
  mdiEye,
  mdiEyeOutline,
  mdiFile,
  mdiFileOutline,
  mdiFileExportOutline,
  mdiFileImportOutline,
  mdiFilter,
  mdiFilterOutline,
  mdiFolderOutline,
  mdiFolderZipOutline,
  mdiFormatAlignCenter,
  mdiFormatAlignJustify,
  mdiFormatAlignLeft,
  mdiFormatAlignRight,
  mdiFormatBold,
  mdiFormatColumns,
  mdiFormatItalic,
  mdiFormatListBulleted,
  mdiFormatListNumbered,
  mdiFormatStrikethrough,
  mdiHelpCircleOutline,
  mdiHistory,
  mdiInbox,
  mdiInformation,
  mdiInformationOutline,
  mdiLabel,
  mdiLock,
  mdiLockOff,
  mdiLogout,
  mdiMagnify,
  mdiMapMarker,
  mdiMenuDown,
  mdiMinus,
  mdiOfficeBuilding,
  mdiPaperclip,
  mdiPencil,
  mdiPhone,
  mdiPlus,
  mdiRedo,
  mdiRefresh,
  mdiReload,
  mdiReply,
  mdiReplyOutline,
  mdiSend,
  mdiSendClockOutline,
  mdiServerSecurity,
  mdiShareOutline,
  mdiStar,
  mdiStarOutline,
  mdiStop,
  mdiSync,
  mdiThumbDownOutline,
  mdiThumbUp,
  mdiThumbUpOutline,
  mdiToolbox,
  mdiTrashCan,
  mdiTrashCanOutline,
  mdiUndo,
  mdiUpload,
  mdiViewDashboardOutline,
} from '@mdi/js'

export const mdiIcons = {
  'mdi-account': mdiAccount,
  'mdi-account-circle-outline': mdiAccountCircleOutline,
  'mdi-account-multiple-outline': mdiAccountMultipleOutline,
  'mdi-account-supervisor': mdiAccountSupervisor,
  'mdi-alert-circle-outline': mdiAlertCircleOutline,
  'mdi-alert-octagon-outline': mdiAlertOctagonOutline,
  'mdi-apps': mdiApps,
  'mdi-arrow-down': mdiArrowDown,
  'mdi-arrow-left': mdiArrowLeft,
  'mdi-arrow-right': mdiArrowRight,
  'mdi-arrow-up': mdiArrowUp,
  'mdi-at': mdiAt,
  'mdi-backup-restore': mdiBackupRestore,
  'mdi-bell': mdiBell,
  'mdi-cached': mdiCached,
  'mdi-calendar': mdiCalendar,
  'mdi-calendar-import-outline': mdiCalendarImportOutline,
  'mdi-card-account-mail-outline': mdiCardAccountMailOutline,
  'mdi-check': mdiCheck,
  'mdi-check-all': mdiCheckAll,
  'mdi-check-circle': mdiCheckCircle,
  'mdi-check-circle-outline': mdiCheckCircleOutline,
  'mdi-chevron-down': mdiChevronDown,
  'mdi-chevron-left': mdiChevronLeft,
  'mdi-chevron-right': mdiChevronRight,
  'mdi-chevron-up': mdiChevronUp,
  'mdi-circle-edit-outline': mdiCircleEditOutline,
  'mdi-circle-small': mdiCircleSmall,
  'mdi-clipboard-multiple-outline': mdiClipboardMultipleOutline,
  'mdi-clipboard-outline': mdiClipboardOutline,
  'mdi-clipboard-plus': mdiClipboardPlus,
  'mdi-clock-outline': mdiClockOutline,
  'mdi-close': mdiClose,
  'mdi-close-circle': mdiCloseCircle,
  'mdi-close-circle-outline': mdiCloseCircleOutline,
  'mdi-code-tags': mdiCodeTags,
  'mdi-cog': mdiCog,
  'mdi-cog-outline': mdiCogOutline,
  'mdi-contacts': mdiContacts,
  'mdi-contacts-outline': mdiContactsOutline,
  'mdi-content-copy': mdiContentCopy,
  'mdi-content-save': mdiContentSave,
  'mdi-content-save-outline': mdiContentSaveOutline,
  'mdi-delete': mdiDelete,
  'mdi-delete-outline': mdiDeleteOutline,
  'mdi-domain': mdiDomain,
  'mdi-dots-horizontal': mdiDotsHorizontal,
  'mdi-dots-vertical': mdiDotsVertical,
  'mdi-download': mdiDownload,
  'mdi-earth': mdiEarth,
  'mdi-email': mdiEmail,
  'mdi-email-check-outline': mdiEmailCheckOutline,
  'mdi-email-fast-outline': mdiEmailFastOutline,
  'mdi-email-open-outline': mdiEmailOpenOutline,
  'mdi-email-outline': mdiEmailOutline,
  'mdi-email-sync-outline': mdiEmailSyncOutline,
  'mdi-eye': mdiEye,
  'mdi-eye-outline': mdiEyeOutline,
  'mdi-file': mdiFile,
  'mdi-file-outline': mdiFileOutline,
  'mdi-file-export-outline': mdiFileExportOutline,
  'mdi-file-import-outline': mdiFileImportOutline,
  'mdi-filter': mdiFilter,
  'mdi-filter-outline': mdiFilterOutline,
  'mdi-folder-outline': mdiFolderOutline,
  'mdi-folder-zip-outline': mdiFolderZipOutline,
  'mdi-format-align-center': mdiFormatAlignCenter,
  'mdi-format-align-justify': mdiFormatAlignJustify,
  'mdi-format-align-left': mdiFormatAlignLeft,
  'mdi-format-align-right': mdiFormatAlignRight,
  'mdi-format-bold': mdiFormatBold,
  'mdi-format-columns': mdiFormatColumns,
  'mdi-format-italic': mdiFormatItalic,
  'mdi-format-list-bulleted': mdiFormatListBulleted,
  'mdi-format-list-numbered': mdiFormatListNumbered,
  'mdi-format-strikethrough': mdiFormatStrikethrough,
  'mdi-help-circle-outline': mdiHelpCircleOutline,
  'mdi-history': mdiHistory,
  'mdi-inbox': mdiInbox,
  'mdi-information': mdiInformation,
  'mdi-information-outline': mdiInformationOutline,
  'mdi-label': mdiLabel,
  'mdi-lock': mdiLock,
  'mdi-lock-off': mdiLockOff,
  'mdi-logout': mdiLogout,
  'mdi-magnify': mdiMagnify,
  'mdi-map-marker': mdiMapMarker,
  'mdi-menu-down': mdiMenuDown,
  'mdi-minus': mdiMinus,
  'mdi-office-building': mdiOfficeBuilding,
  'mdi-paperclip': mdiPaperclip,
  'mdi-pencil': mdiPencil,
  'mdi-phone': mdiPhone,
  'mdi-plus': mdiPlus,
  'mdi-redo': mdiRedo,
  'mdi-refresh': mdiRefresh,
  'mdi-reload': mdiReload,
  'mdi-reply': mdiReply,
  'mdi-reply-outline': mdiReplyOutline,
  'mdi-send': mdiSend,
  'mdi-send-clock-outline': mdiSendClockOutline,
  'mdi-server-security': mdiServerSecurity,
  'mdi-share-outline': mdiShareOutline,
  'mdi-star': mdiStar,
  'mdi-star-outline': mdiStarOutline,
  'mdi-stop': mdiStop,
  'mdi-sync': mdiSync,
  'mdi-thumb-down-outline': mdiThumbDownOutline,
  'mdi-thumb-up': mdiThumbUp,
  'mdi-thumb-up-outline': mdiThumbUpOutline,
  'mdi-toolbox': mdiToolbox,
  'mdi-trash-can': mdiTrashCan,
  'mdi-trash-can-outline': mdiTrashCanOutline,
  'mdi-undo': mdiUndo,
  'mdi-upload': mdiUpload,
  'mdi-view-dashboard-outline': mdiViewDashboardOutline,
}
